region_type = {
    "Allan" : "Rural-Remote",
    "Beaverlodge" : "Rural-Remote",
    "Fermont" : "Rural-Remote",
    "Fort_McKay" : "Rural-Remote",
    "Fox_Creek" : "Rural-Remote",
    "Ingersoll" : "Rural-Remote",
    "LCHVGB" : "Rural-Remote",
    "LCHVGB_Fermont" : "Rural-Remote",
    "Manitouwadge" : "Rural-Remote",
    "Rosetown" : "Rural-Remote",
    "Thamesford" : "Rural-Remote",
    "Thamesford_Ingersoll" : "Rural-Remote",
    "Timmins" : "Rural-Remote",
    "Wollaston_Lake" : "Rural-Remote",
    "Edmonton" : "Urban",
    "Kitchener_Waterloo_Guelph" : "Urban",
    "London" : "Urban",
    "Ottawa_Gatineau" : "Urban",
    "Quebec" : "Urban",
    "Burnaby" : "Metro",
    "Delta" : "Metro",
    "Montreal" : "Metro",
    "North_Shore_Coquitlam" : "Metro",
    "Peel" : "Metro",
    "Richmond" : "Metro",
    "Toronto" : "Metro",
    "Vancouver" : "Metro",
    "Vancouver_Metro" : "Metro",
    "York" : "Metro",



}